### ISSUE TITLE
generate command not working with sails 0.11.0

### ISSUE THREAD

**Issue by maheshchari** [tjwebb/sails-permissions#110]
When i tried to generate it saying generated but there are no generated files in application directory. 
I have tried with both 1.0.19 and 1.3.6 .

**Comment by maheshchari** [comment]
It throwing 

Error: Cannot find module 'D:\work\....\sails-permissions\generator'

**Comment by maheshchari** [comment]
If i give "permissions-api": "node_modules/sails-permissions/generator" in sailsrc it worked fine ,i am not sure in new version sails they changed path
